all: decoder utf8
.PHONY: all

sources = \
  ../src/validate_utf8.sig \
  ../src/validate_utf8.sml \
  ../src/error.sig \
  ../src/error.sml \
  ../src/value_handler.sig \
  ../src/parse_toml.sig \
  ../src/parse_toml_util.sml \
  ../src/parse_toml.sml \
  ../src/value.sig \
  ../src/value.sml \
  ../src/parse_toml_default.sml \
  ../toml.mlb

decoder: decoder.mlb decoder.sml $(sources)
	mlkit -o $@ decoder.mlb

utf8: utf8.mlb utf8.sml $(sources)
	mlkit -o $@ utf8.mlb
