smlsharp = smlsharp

objects = \
  src/validate_utf8.o \
  src/error.o \
  src/parse_toml_util.o \
  src/parse_toml.o \
  src/value.o \
  src/parse_toml_default.o

all: $(objects)
.PHONY: all

%.o: %.sml
	$(smlsharp) -c -o $@ $<
